name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Ensure this matches the name of your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # This is the target branch for GitHub Pages
          FOLDER: . # This specifies the folder from which files will be deployed
          CLEAN: true
